echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-26 and learning DevOps"
echo "Hello, Good morning!"
echo "hi my name is pallavi and this is my 1st practical of the devops"